/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hswt_bp4553_swa_projekt_server_persistence_JNIRegistrationPersistence */

#ifndef _Included_de_hswt_bp4553_swa_projekt_server_persistence_JNIRegistrationPersistence
#define _Included_de_hswt_bp4553_swa_projekt_server_persistence_JNIRegistrationPersistence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hswt_bp4553_swa_projekt_server_persistence_JNIRegistrationPersistence
 * Method:    getAll
 * Signature: ()Ljava/util/Collection;
 */
JNIEXPORT jobject JNICALL Java_de_hswt_bp4553_swa_projekt_server_persistence_JNIRegistrationPersistence_getAll
  (JNIEnv *, jobject);

/*
 * Class:     de_hswt_bp4553_swa_projekt_server_persistence_JNIRegistrationPersistence
 * Method:    insert
 * Signature: (Lde/hswt/bp4553/swa/projekt/model/Registration;)V
 */
JNIEXPORT void JNICALL Java_de_hswt_bp4553_swa_projekt_server_persistence_JNIRegistrationPersistence_insert
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
